# delete all the things from this file that you don't need.
# it's important that the indents are correct - it won't work properly without. You can google serverless.com/framework/docs/providers/aws/guide/serverless.yml/ to check the original to see if the indents are correct. 

service: todo-app-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  tasks:
    handler: handler.tasks
    events: 
      - http:
          path: tasks
          method: get
          cors: true
      - http:
          path: tasks/{taskId}
          method: put
          cors: true
      - http:
          path: tasks
          method: post
          cors: true
      - http:
          path: tasks/{taskId}
          method: delete
          cors: true
